Repository ComposableFi/composable, pull requests merged in 2021-12, with the labels that each got.

#328 Stable release
  .github/workflows/docker-release.yml
  .github/workflows/release-drafter.yml
  Makefile
  docker/Dockerfile
  node/Cargo.toml
Labels: patch

#329 Stable release
  Makefile
Labels: patch

#330 Stable release
  .github/workflows/docker-release.yml
  Makefile
Labels: patch

#344 Workflow to dali
  .github/workflows/Picasso-release.yml
  .github/workflows/dali-chachacha-release.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/runtime-release.yml
  Makefile
Labels: patch

#345 Workflow to dali
  Makefile
  node/Cargo.toml
Labels: patch

#351 Cleanup release
  .github/release-drafter.yml
  .github/workflows/check.yml
Labels: patch

#352 Cleanup release
  .github/release-drafter.yml
Labels: patch

#356 Cleanup release
  .github/workflows/Picasso-release.yml
  .github/workflows/release-drafter.yml
Labels: patch

#357 Setup runtime release
  .github/playbooks/client-upgrade.yml
  .github/playbooks/runtime-upgrade.yml
  .github/workflows/Picasso-release.yml
  .github/workflows/ansible-runner.yml
  .github/workflows/dali-chachacha-release.yml
Labels: minor

#358 Setup runtime release
  .github/workflows/dali-chachacha-release.yml
Labels: patch

#362 Workflow to dali
  .github/workflows/dali-chachacha-release.yml
Labels: patch

#374 Picasso v0.2.0 Release
  Cargo.lock
  docs/benchmarking.md
  frame/assets-registry/Cargo.toml
  frame/assets/Cargo.toml
  frame/call-filter/Cargo.toml
  frame/composable-traits/Cargo.toml
  frame/crowdloan-bonus/Cargo.toml
  frame/crowdloan-rewards/Cargo.toml
  frame/currency-factory/Cargo.toml
  frame/curve-amm/Cargo.toml
  frame/dutch-auction/Cargo.toml
  frame/governance-registry/Cargo.toml
  frame/lending/Cargo.toml
  frame/liquidations/Cargo.toml
  frame/oracle/Cargo.toml
  frame/ping/Cargo.toml
  frame/transaction-fee/Cargo.toml
  frame/vault/Cargo.toml
  integration-tests/Cargo.toml
  node/Cargo.toml
  node/src/chain_spec/picasso.rs
  node/src/command.rs
  node/src/res/dali-chachacha.json
  node/src/res/dali-westend.json
  node/src/service.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/picasso/Cargo.toml
  runtime/picasso/src/lib.rs
  runtime/picasso/src/weights/utility.rs
  runtime/primitives/Cargo.toml
  scripts/polkadot-launch/README.md
  utils/collator-sidecar/Cargo.toml
  utils/faucet-server/Cargo.toml
  utils/faucet-server/src/main.rs
  utils/parachain-utils/Cargo.toml
  utils/parachain-utils/src/main.rs
  utils/subxt-clients/Cargo.toml
Labels: minor

#382 Dali chachacha v1.1.0
  Cargo.lock
  node/Cargo.toml
  node/src/res/dali-chachacha.json
  node/src/res/dali-rococo.json
  node/src/res/dali-westend.json
  node/src/service.rs
Labels: minor

#399 Update ansible picasso
  .maintain/playbooks/picasso-gcp.yaml
Labels: minor

#426 revert ParaId to 2087
  node/src/res/picasso.json
Labels: major
