Repository ComposableFi/composable, pull requests merged in 2022-03, with the labels that each got.

#708 Composable bootnode peerid
  node/src/res/composable.json
Labels: patch, needs-backport

#709 AUTO: Composable bootnode peerid (#708)
  node/src/res/composable.json
Labels: patch, autocreated

#710 Composable bootnode peerid
  .github/workflows/release-rollout.yml
Labels: patch, needs-backport

#711 AUTO: Composable bootnode peerid (#710)
  .github/workflows/release-rollout.yml
Labels: patch, autocreated

#712 Update node permission
  .github/workflows/release-pipeline.yml
  node/src/chain_spec.rs
Labels: patch, needs-backport

#713 AUTO: Update node permission (#712)
  node/src/chain_spec.rs
Labels: patch, autocreated

#716 Use compressed wasm instead of compact
  .github/workflows/check.yml
  .github/workflows/release-pipeline.yml
Labels: needs-backport

#717 AUTO: Use compressed wasm instead of compact (#716)
  .github/workflows/check.yml
  .github/workflows/release-pipeline.yml
Labels: autocreated

#722 AUTO: Update node permission (#720)
  .github/workflows/release-pipeline.yml
  node/src/res/composable.json
Labels: patch, autocreated

#736 Chnage westend bootnode
  node/src/res/composable-westend.json
Labels: patch, needs-backport

#737 AUTO: Chnage westend bootnode (#736)
  node/src/res/composable-westend.json
Labels: patch, autocreated

#741 updating bootnode
  node/src/res/composable-westend.json
Labels: patch, needs-backport

#742 AUTO: updating bootnode (#741)
  node/src/res/composable-westend.json
Labels: patch, autocreated

#657 docker multi-arch
  .github/workflows/docker-release.yml
Labels: patch, needs-backport

#747 AUTO: docker multi-arch (#657)
  .github/workflows/docker-release.yml
Labels: patch, autocreated

#762 Composable ngihtly snapshot
  .github/workflows/docker-release.yml
  .github/workflows/picashot.yml
Labels: needs-backport

#763 AUTO: Composable ngihtly snapshot (#762)
  .github/workflows/docker-release.yml
  .github/workflows/picashot.yml
Labels: autocreated

#792 review runtime versions
  Cargo.lock
  node/Cargo.toml
  runtime/composable/src/lib.rs
  runtime/dali/src/lib.rs
  runtime/picasso/src/lib.rs
Labels: needs-backport

#798 Release take 4
  .github/workflows/devnet-release.yml
  Cargo.lock
  node/Cargo.toml
  runtime/composable/Cargo.toml
  runtime/composable/src/lib.rs
  runtime/dali/Cargo.toml
  runtime/dali/src/lib.rs
  runtime/picasso/Cargo.toml
  runtime/picasso/src/lib.rs
Labels: minor

#810 convert dali-rococo para-id to 2087 (#808)
  node/src/res/dali-rococo.json
Labels: patch

#818 Updating dockerfile
  docker/Dockerfile
Labels: patch, needs-backport

#819 Updating dockerfile
  .github/workflows/docker-release.yml
  docker/Dockerfile
Labels: patch, needs-backport

#820 Updating dockerfile
  .github/workflows/docker-release.yml
Labels: patch, needs-backport

#821 revert composable spec version to 100 for codeSubstitute
  runtime/composable/src/lib.rs
Labels: needs-backport

#822 revert composable spec version to 100 for codeSubstitute (#821)
  runtime/composable/src/lib.rs
Labels: patch

#823 adds codeSubstitute for composable
  dali_runtime.compact.compressed.wasm
  node/src/res/composable.json
Labels: needs-backport
