Repository ComposableFi/composable, pull requests merged in 2022-02, with the labels that each got.

#585 simplify benchmarking
  .github/workflows/benchmark.yml
  .maintain/run_benchmarks.sh
Labels: needs-benchmarks

#593 Update simnode path
  .github/workflows/benchmark.yml
  Makefile
Labels: bug

#600 Update simnode data path
  .github/workflows/label-validator.yml
  .maintain/run_simnode.sh
  Makefile
Labels: patch

#573 mosaic benchmarks
  frame/mosaic/src/benchmarking.rs
  frame/mosaic/src/lib.rs
  frame/mosaic/src/mock.rs
  frame/mosaic/src/tests.rs
  frame/mosaic/src/weights.rs
  runtime/composable/src/lib.rs
  runtime/dali/src/lib.rs
  runtime/dali/src/weights/mod.rs
  runtime/dali/src/weights/mosaic.rs
  runtime/picasso/src/lib.rs
  runtime/picasso/src/weights/balances.rs
  runtime/picasso/src/weights/collator_selection.rs
  runtime/picasso/src/weights/collective.rs
  runtime/picasso/src/weights/democracy.rs
  runtime/picasso/src/weights/frame_system.rs
  runtime/picasso/src/weights/identity.rs
  runtime/picasso/src/weights/indices.rs
  runtime/picasso/src/weights/membership.rs
  runtime/picasso/src/weights/multisig.rs
  runtime/picasso/src/weights/scheduler.rs
  runtime/picasso/src/weights/session.rs
  runtime/picasso/src/weights/timestamp.rs
  runtime/picasso/src/weights/treasury.rs
  runtime/picasso/src/weights/utility.rs
Labels: needs-benchmarks, needs-simnode

#606 Create clean release
  .github/workflows/release-pipeline.yml
  .maintain/client_release.sh
  .maintain/playbooks/client-upgrade.yml
Labels: patch

#608 CU-1wty1h0 liquidations test/bench/runtime - required by lending
  Cargo.lock
  frame/dutch-auction/src/tests.rs
  frame/lending/README.md
  frame/liquidations/Cargo.toml
  frame/liquidations/README.md
  frame/liquidations/src/benchmarking.rs
  frame/liquidations/src/lib.rs
  frame/liquidations/src/mock/currency.rs
  frame/liquidations/src/mock/governance_registry.rs
  frame/liquidations/src/mock/mod.rs
  frame/liquidations/src/mock/runtime.rs
  frame/liquidations/src/tests.rs
  runtime/dali/Cargo.toml
  runtime/dali/src/lib.rs
  runtime/dali/src/weights/liqudations.rs
Labels: needs-benchmarks

#624 Update Simnode Implementation
  Cargo.lock
  integration-tests/simnode/Cargo.toml
  integration-tests/simnode/src/chain/dali.rs
  integration-tests/simnode/src/chain/picasso.rs
  integration-tests/simnode/src/main.rs
  integration-tests/simnode/src/tests/runtime_upgrade.rs
  runtime/dali/Cargo.toml
  runtime/dali/src/lib.rs
  runtime/picasso/Cargo.toml
  runtime/picasso/src/lib.rs
Labels: needs-backport

#626 fix diffing on release-pipeline
  .maintain/check_runtime.sh
  .maintain/client_release.sh
  .maintain/common/lib.sh
  .maintain/run_benchmarks.sh
  .maintain/run_simnode.sh
  .maintain/runtime_release.sh
Labels: needs-backport

#627 Ci upgrade
  .github/workflows/ansible-runner.yml
  .github/workflows/docker-release.yml
  .github/workflows/release-pipeline.yml
  Makefile
  docker/Dockerfile
Labels: patch

#631 adds chainspec for rococo
  node/src/res/dali-rococo.json
Labels: needs-backport

#635 [backport]: Fix simnode & benchmarking trigger (#629)
  .github/workflows/benchmark.yml
  .github/workflows/simnode.yml
  .github/workflows/slash.yml
Labels: autocreated

#616 lending into runtime
  Cargo.lock
  docs/benchmarking.md
  frame/assets/Cargo.toml
  frame/composable-traits/src/defi.rs
  frame/composable-traits/src/lending/mod.rs
  frame/composable-traits/src/oracle.rs
  frame/crowdloan-rewards/Cargo.toml
  frame/currency-factory/Cargo.toml
  frame/curve-amm/Cargo.toml
  frame/dutch-auction/src/mock/runtime.rs
  frame/lending/Cargo.toml
  frame/lending/proptest-regressions/tests.txt
  frame/lending/src/benchmarking.rs
  frame/lending/src/currency.rs
  frame/lending/src/lib.rs
  frame/lending/src/mocks/currency.rs
  frame/lending/src/mocks/mod.rs
  frame/lending/src/mocks/oracle.rs
  frame/lending/src/models.rs
  frame/lending/src/setup.rs
  frame/lending/src/tests.rs
  frame/liquidations/src/lib.rs
  frame/liquidations/src/mock/runtime.rs
  frame/mosaic/Cargo.toml
  frame/oracle/src/benchmarking.rs
  frame/oracle/src/lib.rs
  frame/oracle/src/tests.rs
  frame/vault/Cargo.toml
  integration-tests/Cargo.toml
  runtime/common/src/lib.rs
  runtime/composable/Cargo.toml
  runtime/composable/src/lib.rs
  runtime/dali/Cargo.toml
  runtime/dali/src/lib.rs
  runtime/dali/src/weights/lending.rs
  runtime/dali/src/weights/liqudations.rs
  runtime/picasso/Cargo.toml
  runtime/picasso/src/lib.rs
  scripts/run_benchmarks.sh
  utils/collator-sidecar/Cargo.toml
  utils/parachain-utils/Cargo.toml
  utils/price-feed/Cargo.toml
Labels: angular

#644 Add bootnode peerid rococo
  node/src/res/dali-rococo.json
Labels: patch

#648 enables collator-sidecar
  Cargo.lock
  Cargo.toml
  scripts/polkadot-launch/composable.json
  utils/collator-sidecar/Cargo.toml
Labels: needs-backport

#646 Update make version
  .github/workflows/docker-release.yml
  Makefile
  node/src/res/dali-rococo.json
Labels: patch, needs-backport

#649 AUTO: enables collator-sidecar (#648)
  Cargo.lock
  Cargo.toml
  scripts/polkadot-launch/composable.json
  utils/collator-sidecar/Cargo.toml
Labels: autocreated

#650 AUTO: Update dali-rococo-bootnodes
  .github/workflows/docker-release.yml
  Makefile
  node/src/res/dali-rococo.json
Labels: patch, autocreated

#658 Ansible update
  .github/workflows/docker-release.yml
  .github/workflows/release-pipeline.yml
  .github/workflows/release-rollout.yml
  .maintain/playbooks/client-upgrade.yml
  node/src/res/dali-rococo.json
Labels: patch, needs-backport

#659 AUTO: Ansible update (#658)
  .github/workflows/docker-release.yml
  .github/workflows/release-pipeline.yml
  .github/workflows/release-rollout.yml
  .maintain/playbooks/client-upgrade.yml
  node/src/res/dali-rococo.json
Labels: patch, autocreated

#665 AUTO: Ansible update (#664)
  node/src/res/dali-rococo.json
Labels: patch, autocreated

#678 Updated Crowdloan Readme
  frame/crowdloan-rewards/README.md
Labels: documentation

#676 Ben/currency docs
  frame/lending/src/currency.rs
  frame/lending/src/lib.rs
  frame/lending/src/mocks/mod.rs
  frame/lending/src/tests.rs
  integration-tests/local-integration-tests/Cargo.toml
  runtime/composable/Cargo.toml
  runtime/dali/Cargo.toml
Labels: documentation

#683 CU-263dx6e - Mosaic assets mapping
  frame/mosaic/src/benchmarking.rs
  frame/mosaic/src/lib.rs
  frame/mosaic/src/mock.rs
  frame/mosaic/src/tests.rs
  frame/mosaic/src/weights.rs
  runtime/common/src/lib.rs
  runtime/composable/src/weights/balances.rs
  runtime/composable/src/weights/collator_selection.rs
  runtime/composable/src/weights/collective.rs
  runtime/composable/src/weights/democracy.rs
  runtime/composable/src/weights/frame_system.rs
  runtime/composable/src/weights/indices.rs
  runtime/composable/src/weights/membership.rs
  runtime/composable/src/weights/scheduler.rs
  runtime/composable/src/weights/session.rs
  runtime/composable/src/weights/timestamp.rs
  runtime/composable/src/weights/treasury.rs
  runtime/composable/src/weights/utility.rs
  runtime/dali/src/lib.rs
  runtime/dali/src/weights/balances.rs
  runtime/dali/src/weights/bonded_finance.rs
  runtime/dali/src/weights/collator_selection.rs
  runtime/dali/src/weights/collective.rs
  runtime/dali/src/weights/currency_factory.rs
  runtime/dali/src/weights/democracy.rs
  runtime/dali/src/weights/dutch_auction.rs
  runtime/dali/src/weights/frame_system.rs
  runtime/dali/src/weights/identity.rs
  runtime/dali/src/weights/indices.rs
  runtime/dali/src/weights/liquidations.rs
  runtime/dali/src/weights/membership.rs
  runtime/dali/src/weights/mosaic.rs
  runtime/dali/src/weights/multisig.rs
  runtime/dali/src/weights/oracle.rs
  runtime/dali/src/weights/scheduler.rs
  runtime/dali/src/weights/session.rs
  runtime/dali/src/weights/timestamp.rs
  runtime/dali/src/weights/treasury.rs
  runtime/dali/src/weights/utility.rs
  runtime/dali/src/weights/vault.rs
  runtime/picasso/src/weights/balances.rs
  runtime/picasso/src/weights/bonded_finance.rs
  runtime/picasso/src/weights/collator_selection.rs
  runtime/picasso/src/weights/collective.rs
  runtime/picasso/src/weights/currency_factory.rs
  runtime/picasso/src/weights/democracy.rs
  runtime/picasso/src/weights/frame_system.rs
  runtime/picasso/src/weights/identity.rs
  runtime/picasso/src/weights/indices.rs
  runtime/picasso/src/weights/membership.rs
  runtime/picasso/src/weights/multisig.rs
  runtime/picasso/src/weights/scheduler.rs
  runtime/picasso/src/weights/session.rs
  runtime/picasso/src/weights/timestamp.rs
  runtime/picasso/src/weights/treasury.rs
  runtime/picasso/src/weights/utility.rs
Labels: needs-benchmarks
