Repository ComposableFi/composable, pull requests merged in 2022-04, with the labels that each got.

#828 docs(mdbook): Moved Angular documentation from ClickUp to mdbook.
  book/src/SUMMARY.md
  book/src/products/angular/angular-token.md
  book/src/products/angular/foreign-assets.md
  book/src/products/angular/img/angular_logo-1500x500.png
  book/src/products/angular/img/technical-specification/graph-curved-model.png
  book/src/products/angular/img/technical-specification/graph-double-exponent-model.png
  book/src/products/angular/img/technical-specification/graph-jump-model.png
  book/src/products/angular/product-brief.md
  book/src/products/angular/socials.md
  book/src/products/angular/technical-specification.md
  book/src/products/angular/technical-specification/collateral.md
  book/src/products/angular/technical-specification/collateral/nfts.md
  book/src/products/angular/technical-specification/liquidations.md
  book/src/products/angular/technical-specification/liquidations/implementation.md
  book/src/products/angular/technical-specification/liquidations/liquidation-interface.md
  book/src/products/angular/technical-specification/liquidations/liquidation-interface/ibc.md
  book/src/products/angular/technical-specification/liquidations/liquidation-interface/xcm.md
  book/src/products/angular/technical-specification/models.md
  book/src/products/angular/technical-specification/oracle.md
  book/src/products/angular/technical-specification/pools.md
  book/src/products/angular/technical-specification/references.md
  book/src/products/angular/technical-specification/references/COM-LendingFeatures-030122-1046.pdf
  book/src/products/angular/technical-specification/undercollateralized-loans-leverage.md
Labels: documentation, angular

#853 Change composable bootnode peerid
  .github/workflows/docker-release.yml
  node/src/res/composable.json
Labels: patch, needs-backport

#854 update download path from github releases
  docker/Dockerfile
Labels: patch

#875 use cumulus fork, with fix for POV construction
  Cargo.lock
  Cargo.toml
  simnode/common/src/events.rs
Labels: needs-backport

#877 build new release
  runtime/composable/src/lib.rs
Labels: patch, needs-backport

#879 Trigger new build
  .github/workflows/cherry-pick.yml
Labels: needs-backport

#880 Trigger new build
  .github/workflows/cherry-pick.yml
Labels: needs-backport

#881 Trigger new build
  .github/workflows/cherry-pick.yml
Labels: needs-backport

#868 Docker update
  .github/workflows/docker-release.yml
  docker/Dockerfile
Labels: patch
