Repository ComposableFi/composable, pull requests merged in 2022-01, with the labels that each got.

#447 One release
  .github/workflows/Picasso-release.yml
  .github/workflows/ansible-runner.yml
  .github/workflows/check.yml
  .github/workflows/client-release.yml
  .github/workflows/release-drafter.yml
  .github/workflows/runtime-check.yml
  .maintain/playbooks/client-upgrade.yml
  Makefile
  docker/Dockerfile
  node/Cargo.toml
Labels: minor

#452 Hotfix
  .github/workflows/check.yml
  .github/workflows/client-release.yml
  .maintain/playbooks/client-upgrade.yml
Labels: hotfix

#453 Update event triggers
  .github/workflows/ansible-runner.yml
  .github/workflows/check.yml
  .github/workflows/client-release.yml
  .github/workflows/runtime-check.yml
  .maintain/check_runtime.sh
Labels: patch

#456 Release 1.3.0
  .github/workflows/Picasso-release.yml
  .github/workflows/check.yml
  .github/workflows/release-drafter.yml
  .github/workflows/runtime-check.yml
  .maintain/check_runtime.sh
  runtime/picasso/src/weights/balances.rs
  runtime/picasso/src/weights/democracy.rs
Labels: major

#461 Feature/simnode workflow
  .github/workflows/Picasso-release.yml
  .github/workflows/check.yml
  .github/workflows/client-release.yml
  .github/workflows/picashot.yml
  .github/workflows/runtime-check.yml
  .maintain/check_runtime.sh
  .maintain/files/backup.sh
  .maintain/playbooks/picashot.yml
  docker/Dockerfile
Labels: minor

#520 Seun fix scripts
  .github/workflows/benchmark.yml
  .github/workflows/simnode.yml
  .maintain/check_runtime.sh
  .maintain/client_release.sh
  .maintain/common/lib.sh
  .maintain/runtime_release.sh
Labels: major

#521 update release drafter action
  .github/workflows/release-drafter.yml
Labels: minor

#563 make benchmark to work with labels
  .github/workflows/benchmark.yml
Labels: needs-benchmarks
