Repository ComposableFi/composable, pull requests merged in 2023-09, with the labels that each got.

#4115 chore: remove last reference to lazy-static; use workspace hex-literal
  code/Cargo.toml
  code/integration-tests/local-integration-tests/Cargo.toml
  code/parachain/frame/airdrop/Cargo.toml
  code/parachain/frame/cosmwasm/Cargo.toml
  code/parachain/frame/crowdloan-rewards/Cargo.toml
  code/parachain/frame/dutch-auction/Cargo.toml
  code/parachain/frame/lending/Cargo.toml
  code/parachain/frame/liquidations/Cargo.toml
  code/parachain/runtime/composable/Cargo.toml
  code/parachain/runtime/picasso/Cargo.toml
  code/parachain/runtime/primitives/Cargo.toml
Labels: misc

#4112 feat(xcvm): define helper proto::define_conversion macro
  code/xcvm/lib/core/src/proto.rs
  code/xcvm/lib/core/src/proto/xcvm.rs
Labels: misc

#4110 docs(council-update): OpenGov-Soon-council-change
  docs/docs/networks/picasso/governance.md
Labels: misc, stale-item

#4124 docs(addition): adding faqs to docs
  docs/docs/user-guides/composableFAQ.png
  docs/docs/user-guides/faq.md
Labels: misc

#4134 docs(license): add-license-to-cw-code
  code/parachain/frame/cosmwasm/License.md
Labels: misc

#4135 docs(addition): cw inspiration Update Readme
  code/parachain/frame/cosmwasm/README.md
Labels: misc

#4146 docs(updates): update cli cmds + config for formulae
  docs/docs/developer-guides/cosmwasm-cli.md
Labels: misc

#4147 docs(centauri): revamp composable ibc docs
  docs/docs/ecosystem/composable-grants.md
  docs/docs/intro.md
  docs/docs/networks/picasso/crowdloan.md
  docs/docs/networks/picasso/token-transparency.md
  docs/docs/networks/picasso/tokenomics.md
  docs/docs/products/centauri-overview.md
  docs/docs/products/centauri/Dotsama-ibc.md
  docs/docs/products/composable-ibc.md
  docs/docs/products/composable-ibc/cosmos-ibc.md
  docs/docs/products/composable-ibc/cosmos11-BEEFY-COSMOS-IBC-light-client.md
  docs/docs/products/composable-ibc/hyperspace-relayer.md
  docs/docs/products/composable-ibc/light-clients.md
  docs/docs/products/composable-ibc/merkle-mountain-ranges.md
  docs/docs/products/composable-ibc/near-ibc-bridge.md
  docs/docs/products/composable-ibc/polkadot-kusama-ibc.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: misc

#4153 feat(ibc): Update composable-ibc revision
  code/Cargo.lock
  code/Cargo.toml
  code/parachain/runtime/composable/src/version.rs
  code/parachain/runtime/picasso/src/version.rs
  flake.lock
  flake.nix
Labels: Misc

#4154 docs(edits): cleanup for cvm first
  docs/docs/ecosystem/rfp-canonical-stablecoin-design-and-integration.md
  docs/docs/ecosystem/rfp-explorer.md
  docs/docs/intro.md
  docs/docs/networks/centauri-chain.md
  docs/docs/networks/composable-parachain-overview.md
  docs/docs/networks/picasso-parachain-overview.md
  docs/docs/products/composable-technical-stack.png
  docs/docs/products/cosmwasm/synergy-with-ibc-for-cvm.md
  docs/docs/products/cvm.md
  docs/docs/products/cvm/use-cases/swap.mdx
  docs/docs/products/pablo-overview.md
  docs/docs/products/technical-stack-overview.md
  docs/docs/products/xcvm.md
  docs/docs/products/xcvm/cross-chain-lending-example-composable-xcvm.jpg
  docs/docs/products/xcvm/how-it-works.md
  docs/docs/products/xcvm/how-xcvm-works.jpg
  docs/docs/user-guides/centauri-guide.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: Misc

#4158 docs(addition): add eth brief overview
  docs/docs/products/composable-ibc/cosmos-ibc.md
  docs/docs/products/composable-ibc/ethereum-ibc.md
  docs/docs/products/composable-ibc/hyperspace-relayer.md
  docs/sidebars.js
Labels: Misc

#4165 docs(cvm): make edits to spec + more
  docs/docs/ecosystem/the-composable-team.md
  docs/docs/products/composable-ibc/ethereum-ibc.md
  docs/docs/products/cvm.md
  docs/docs/products/cvm/specification.md
Labels: Misc
