Repository ComposableFi/composable, pull requests merged in 2023-12, with the labels that each got.

#4383 docs: fix typos
  docs/docs/codespaces.md
  docs/docs/ecosystem/business-line-development.md
  docs/docs/intro.md
  docs/docs/technology/cvm.md
  docs/docs/technology/liquid-staking.md
  docs/docs/user-guides/how-to-trade-pica-on-pablo.md
Labels: Stale-item

#4382 docs(update): add OG parameters + intro to Mantis
  README.md
  docs/docs/mantis/overview.md
  docs/docs/networks/picasso/governance.md
Labels: Misc, Stale-item

#4386 chore(cli): Propagate CLI pruning flags to relaychain
  code/parachain/node/src/command.rs
Labels: Misc

#4389 docs(UG): update user guides + additions
  docs/docs/user-guides/centauri-guide.md
  docs/docs/user-guides/centauri-transfers.md
  docs/docs/user-guides/dot-lp-guide.md
  docs/docs/user-guides/how-to-provide-liquidity.md
  docs/docs/user-guides/images-centauri-chain/stake-1.png
  docs/docs/user-guides/images-centauri-chain/stake-2.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-1.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-10.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-2.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-3.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-4.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-5.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-6.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-7.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-8.png
  docs/docs/user-guides/images-centauri-guide/centauri-guide-9.png
  docs/docs/user-guides/images-dot-lp-guide/ibc-dot-picasso.png
  docs/docs/user-guides/images-dot-lp-guide/pablo-lp-1.png
  docs/docs/user-guides/images-dot-lp-guide/pablo-lp-2.png
  docs/docs/user-guides/images-dot-lp-guide/stake-3.png
  docs/docs/user-guides/images-trustless-transfer/trustless-transfer.png
  docs/docs/user-guides/keplr-guide.md
  docs/docs/user-guides/trustless-transfers.md
  docs/sidebars.js
Labels: Misc
