Repository ComposableFi/composable, pull requests merged in 2023-05, with the labels that each got.

#3537 chore: update to polkadot v0.9.39
  code/Cargo.lock
  code/Cargo.toml
  code/integration-tests/local-integration-tests/Cargo.toml
Labels: Parachain Team

#3550 Migrate CW docs to CW section
  docs/docs/products/cosmwasm/writing-smart-contracts-with-cosmwasm.md
  docs/sidebars.js
Labels: D-docs, misc

#3545 Update-LP-guide-and-images
  docs/docs/user-guides/how-to-provide-liquidity.md
  docs/docs/user-guides/images-how-to-provide-liquidity/add-liquidity.png
  docs/docs/user-guides/images-how-to-provide-liquidity/confirm-supply.png
  docs/docs/user-guides/images-how-to-provide-liquidity/pica-ksm-pool.png
  docs/docs/user-guides/images-how-to-provide-liquidity/pool-page.png
  docs/docs/user-guides/images-how-to-provide-liquidity/sign-transaction.jpg
  docs/docs/user-guides/images-how-to-provide-liquidity/sign-transaction.png
  docs/docs/user-guides/images-how-to-provide-liquidity/title.png
  docs/docs/user-guides/images-how-to-provide-liquidity/transaction-details.png
  docs/docs/user-guides/images-how-to-provide-liquidity/transaction-finalized.png
  docs/docs/user-guides/images-how-to-provide-liquidity/transaction-initiated.png
Labels: D-docs, misc

#3544 Update tokenomics.md - docs edit
  docs/docs/parachains/picasso/tokenomics.md
Labels: D-docs, misc

#3561 release v6.10021.0 along with release configuration improvements
  .github/pull_request_template.md
  code/Cargo.lock
  code/Cargo.toml
  code/parachain/runtime/composable/src/version.rs
  code/parachain/runtime/picasso/src/version.rs
  flake/release.nix
  terraform/github.com/labels.tf
  terraform/github.com/team.tf
Labels: misc

#3554 update-trading-guide
  docs/docs/user-guides/centauri-guide.md
  docs/docs/user-guides/how-to-trade-pica-on-pablo.md
  docs/docs/user-guides/images-how-to-trade/confirm-swap.png
  docs/docs/user-guides/images-how-to-trade/sign-transaction.jpg
  docs/docs/user-guides/images-how-to-trade/sign-transaction.png
  docs/docs/user-guides/images-how-to-trade/swap-page.jpg
  docs/docs/user-guides/images-how-to-trade/swap-page.png
  docs/docs/user-guides/images-how-to-trade/title.jpg
  docs/docs/user-guides/images-how-to-trade/token-select.png
  docs/docs/user-guides/images-how-to-trade/transaction-details.png
  docs/docs/user-guides/images-how-to-trade/transaction-finalized.png
  docs/docs/user-guides/images-how-to-trade/transaction-initiated.png
  docs/docs/user-guides/images-how-to-trade/transaction-settings.png
Labels: D-docs, misc

#3585 reverted 3 last commits into main because main is super broken
  .github/workflows/build-test-deploy.yml
  code/Cargo.lock
  code/Cargo.toml
  code/integration-tests/local-integration-tests/Cargo.toml
  code/parachain/frame/assets/rpc/src/lib.rs
  code/parachain/frame/cosmwasm/rpc/src/lib.rs
  code/parachain/frame/cosmwasm/src/benchmarking.rs
  code/parachain/frame/cosmwasm/src/lib.rs
  code/parachain/frame/cosmwasm/src/mock.rs
  code/parachain/frame/cosmwasm/src/tests/extrinsics.rs
  code/parachain/frame/cosmwasm/src/tests/helpers.rs
  code/parachain/frame/crowdloan-rewards/rpc/src/lib.rs
  code/parachain/frame/dex-router/src/benchmarking.rs
  code/parachain/frame/dex-router/src/tests.rs
  code/parachain/frame/dutch-auction/src/lib.rs
  code/parachain/frame/dutch-auction/src/mock/runtime.rs
  code/parachain/frame/farming/src/benchmarking.rs
  code/parachain/frame/farming/src/lib.rs
  code/parachain/frame/farming/src/tests.rs
  code/parachain/frame/lending/rpc/src/lib.rs
  code/parachain/frame/lending/src/mocks/general.rs
  code/parachain/frame/lending/src/mocks/offchain.rs
  code/parachain/frame/liquidations/src/mock/runtime.rs
  code/parachain/frame/oracle/src/tests.rs
  code/parachain/frame/pablo/rpc/src/lib.rs
  code/parachain/frame/pablo/src/benchmarking.rs
  code/parachain/frame/pablo/src/test/common_test_functions.rs
  code/parachain/frame/pablo/src/test/dual_asset_constant_product_tests.rs
  code/parachain/frame/pablo/src/test/dual_asset_constant_product_tests_new.rs
  code/parachain/frame/pablo/src/test/pablo_tests.rs
  code/parachain/frame/reward/rpc/src/lib.rs
  code/parachain/frame/staking-rewards/rpc/src/lib.rs
  code/parachain/frame/transaction-payment/rpc/src/lib.rs
  code/parachain/node/src/client.rs
  code/parachain/node/src/service.rs
  code/parachain/runtime/composable/Cargo.toml
  code/parachain/runtime/composable/src/gates.rs
  code/parachain/runtime/composable/src/governance.rs
  code/parachain/runtime/composable/src/ibc.rs
  code/parachain/runtime/composable/src/lib.rs
  code/parachain/runtime/composable/src/weights/ibc.rs
  code/parachain/runtime/picasso/Cargo.toml
  code/parachain/runtime/picasso/src/fees.rs
  code/parachain/runtime/picasso/src/gates.rs
  code/parachain/runtime/picasso/src/governance.rs
  code/parachain/runtime/picasso/src/ibc.rs
  code/parachain/runtime/picasso/src/lib.rs
  code/parachain/runtime/picasso/src/weights/ibc.rs
  code/parachain/runtime/picasso/src/xcmp.rs
  docs/docs/internal/custom-rpcs.md
  inputs/paritytech/substrate.nix
Labels: misc

#3590 Re added CosmWasm RPC and Runtime with fixes with CI improvements
  .github/pull_request_template.md
  .github/workflows/build-test-deploy-flaky.yml
  code/Cargo.lock
  code/Cargo.toml
  code/parachain/frame/cosmwasm/src/benchmarking.rs
  code/parachain/frame/cosmwasm/src/lib.rs
  code/parachain/frame/cosmwasm/src/mock.rs
  code/parachain/frame/cosmwasm/src/tests/extrinsics.rs
  code/parachain/frame/cosmwasm/src/tests/helpers.rs
  code/parachain/frame/dex-router/src/benchmarking.rs
  code/parachain/frame/dex-router/src/tests.rs
  code/parachain/runtime/composable/src/version.rs
  code/parachain/runtime/picasso/Cargo.toml
  code/parachain/runtime/picasso/src/fees.rs
  code/parachain/runtime/picasso/src/ibc.rs
  code/parachain/runtime/picasso/src/lib.rs
  code/parachain/runtime/picasso/src/version.rs
  code/parachain/runtime/picasso/src/xcmp.rs
  inputs/paritytech/substrate.nix
  terraform/github.com/branches.tf
Labels: misc

#3591 Release commit with some cleanup to trigger build
  rfcs/0011-releases.md
Labels: misc

#3593 CI fixes, optimizations, clean up, USD usage reduction
  .github/workflows/pr-workflow-check.yaml
  .github/workflows/pr-workflow-fork.yaml
  .github/workflows/pr-workflow.yml
  code/Cargo.lock
  code/Cargo.toml
  code/integration-tests/runtime-tests/package.json
  code/integration-tests/runtime-tests/runtime-tests.nix
  code/integration-tests/runtime-tests/test/tests/currencyFactory/currencyFactoryTests.ts
  code/integration-tests/runtime-tests/test/tests/currencyFactory/test_configuration.json
  code/integration-tests/runtime-tests/test/tests/democracy/democracyTests.ts
  code/integration-tests/runtime-tests/test/tests/democracy/test_configuration.json
  code/integration-tests/runtime-tests/test/tests/mosaic/mosaicTests.ts
  code/integration-tests/runtime-tests/test/tests/mosaic/testHandlers/mosaicTestHelper.ts
  code/integration-tests/runtime-tests/test/tests/mosaic/test_configuration.json
  code/utils/price-feed/Cargo.toml
  code/utils/price-feed/price-feed.nix
  code/utils/price-feed/src/feed/composable.rs
  flake/dev-shells.nix
  flake/live.nix
Labels: misc

#3606 release candidate 7.10023.1, requires runtime upgrade and node deploy for RPC, and FE sync
  code/Cargo.lock
  code/Cargo.toml
  terraform/github.com/team.tf
Labels: misc

#3602 satemine and statemint in devnets for usdt, and improvement on some `look and feel` of CI (really no changes, just more green look)
  .github/workflows/build-test-deploy-flaky.yml
  .github/workflows/pr-workflow-check.yaml
  .github/workflows/pr-workflow-fork.yaml
  .github/workflows/pr-workflow.yml
  RELEASE.md
  code/integration-tests/runtime-tests/package.json
  code/integration-tests/runtime-tests/runtime-tests.nix
  code/integration-tests/runtime-tests/test/tests/examples/querySystemAccountTests.ts
  flake.lock
  flake.nix
  flake/all.nix
  flake/check.nix
  flake/zombienet.nix
  inputs/paritytech/cumulus.nix
  inputs/paritytech/statemine.nix
  inputs/paritytech/zombienet/default.nix
  rfcs/0011-releases.md
Labels: misc

#3620 pallet-ibc: adjust rate limit based on decimal places
  code/parachain/runtime/composable/src/ibc.rs
  code/parachain/runtime/picasso/src/ibc.rs
Labels: Parachain Team, Bridging Team

#3608 made limited democracy(oligarchy) when voting can be created by Council or Tech collectives, relaxed Picasso democracy to be executable
  RELEASE.md
  code/parachain/frame/composable-traits/src/account_proxy.rs
  code/parachain/runtime/composable/src/gates.rs
  code/parachain/runtime/composable/src/governance.rs
  code/parachain/runtime/picasso/src/gates.rs
  code/parachain/runtime/picasso/src/governance.rs
  inputs/paritytech/substrate.nix
Labels: D-on-chain

#3616 Release candidate 7.10024.0 commit with some fixes and debug improvements for CosmWasm tooling
  .github/workflows/pr-workflow.yml
  code/Cargo.lock
  code/Cargo.toml
  code/parachain/frame/cosmwasm/src/lib.rs
  code/parachain/runtime/composable/src/version.rs
  code/parachain/runtime/picasso/src/version.rs
  docs/docs/products/cosmwasm/deploy-and-run-cosmwasm-contracts-with-pdjs.md
  inputs/paritytech/zombienet/default.nix
Labels: misc

#3630 release candidate tagged commit 7.10025.0
  code/Cargo.lock
  code/Cargo.toml
  code/parachain/runtime/composable/src/version.rs
  code/parachain/runtime/picasso/src/version.rs
Labels: misc

#3634 NoneFlatFee for picasso runtime
  code/parachain/runtime/picasso/src/ibc.rs
  code/parachain/runtime/picasso/src/lib.rs
Labels: misc

#3628 fixed hyperspace run along with statemine by using proper version of local zombienet devnet
  .github/workflows/pr-workflow-check.yaml
  devnets/specs/centauri.nix
  flake.lock
  flake.nix
  flake/zombienet.nix
  tools/devnet-tools.nix
Labels: misc

#3626 minor-docs-edit
  docs/docs/parachains/picasso/token-transparency.md
  docs/docs/products/centauri/Dotsama-ibc.md
  docs/docs/user-guides/centauri-guide.md
Labels: D-docs, misc

#3638 cw-guide
  docs/docs/developer-guides/cosmwasm-cli.md
  docs/docs/developer-guides/cosmwasm/new-project.md
  docs/docs/developer-guides/cosmwasm/walkthrough.md
  docs/sidebars.js
Labels: D-docs, misc

#3636 release candidate 7.10027
  code/Cargo.lock
  code/Cargo.toml
  code/parachain/runtime/composable/src/version.rs
  code/parachain/runtime/picasso/src/version.rs
  devnets/specs/centauri.nix
  inputs/centauri/composable.patch
  inputs/centauri/flake-module.nix
Labels: misc

#3649 update version from 10027 to 10028
  code/Cargo.lock
  code/Cargo.toml
  code/parachain/runtime/composable/src/version.rs
  code/parachain/runtime/picasso/src/version.rs
Labels: misc

#3654 Removed staking tab from Picasso
  frontend/apps/picasso/components/Molecules/NavBar.tsx
  frontend/apps/picasso/pages/staking/index.tsx
Labels: misc
